<?xml version='1.0' encoding='iso-8859-1'?>
    <rows> 
    	<head> 
            <column width="100" type="ed" align="right" color="white" sort="str">Quote Name</column> 
          	<column width="70" type="ed" align="right" color="white" sort="str">Quote Type</column> 
          	<column width="50" type="ed" align="right" color="white" sort="str">Number of Country</column> 
          	<column width="50" type="ed" align="right" color="white" sort="str">Number of Options</column> 
          	<column width="70" type="ed" align="right" color="white" sort="str">Quote Date</column> 
          	<column width="100" type="ed" align="right" color="white" sort="str">Recepient Name</column> 
          	<column width="100" type="ed" align="right" color="white" sort="str">Recepient Email</column> 
          	<column width="100" type="ed" align="right" color="white" sort="str">Company Name</column> 
          	<column width="70" type="ed" align="right" color="white" sort="str">Quote Value</column> 
          	<column width="100" type="ed" align="right" color="white" sort="str">Status</column> 
            <column width="70" type="ed" align="right" color="white" sort="str">Created Date</column> 
			<column width="70" type="ed" align="right" color="white" sort="str">Written By</column> 
            <settings> 
                    <colwidth>20%</colwidth> 
            </settings> 
        </head> 
        <userdata name="NameOfGlobalUserDataBlock"></userdata> 
        <row id="1"> 
            <userdata name="NameOfRowUserDataBlock"></userdata> 
			<cell>JC Penny Consumers</cell> 
            <cell>Translation</cell> 
            <cell>10</cell>
            <cell>5</cell>
            <cell>2011-09-25</cell>
            <cell>Tom Cruise</cell>
            <cell>tom@cruise.com</cell>
            <cell>Hollywood Inc</cell>
            <cell>$6,564.00</cell>
            <cell>Pending Client Review</cell>
            <cell>2011-09-24</cell> 
			<cell>Joan Bingsly</cell>
        </row>
        <row id="2"> 
            <userdata name="NameOfRowUserDataBlock"></userdata> 
			<cell>UHAUL Trucks</cell> 
            <cell>Full Service</cell> 
            <cell>7</cell>
            <cell>2</cell>
            <cell>2011-10-25</cell>
            <cell>Adam Sandler</cell>
            <cell>adam@jokes.com</cell>
            <cell>Gym Inc</cell>
            <cell>$8,545.00</cell>
             <cell><![CDATA[<font color="green"><strong>Accepted</strong></font>]]></cell>
            <cell>2011-09-24</cell> 
			<cell>Mike Rust</cell>
        </row>
        <row id="3"> 
            <userdata name="NameOfRowUserDataBlock"></userdata> 
			<cell>Virgin Mobile Users</cell> 
            <cell>Programming</cell> 
            <cell>2</cell>
            <cell>7</cell>
            <cell>2011-09-25</cell>
            <cell>Richard Branson</cell>
            <cell>richard@virgin.com</cell>
            <cell>Virgin Atlantic Inc</cell>
            <cell>$63,564.00</cell>
             <cell><![CDATA[<font color="blue"><strong>Revision Requested</strong></font>]]></cell>
            <cell>2011-09-24</cell> 
			<cell>Mike Rust</cell>
        </row>
        <row id="4"> 
            <userdata name="NameOfRowUserDataBlock"></userdata> 
			<cell>T-Mobile</cell> 
            <cell>Panel</cell> 
            <cell>3</cell>
            <cell>1</cell>
            <cell>2011-09-25</cell>
            <cell>Tony Blaire</cell>
            <cell>tony@uk.com</cell>
            <cell>British Inteligence</cell>
            <cell>$6,564.00</cell>
          	 <cell><![CDATA[<font color="red"><strong>Rejected</strong></font>]]></cell>
            <cell>2011-09-24</cell> 
			<cell>Mike Rust</cell>
        </row>
        <row id="5"> 
            <userdata name="NameOfRowUserDataBlock"></userdata> 
			<cell>Movie Viewers</cell> 
            <cell>CATI</cell> 
            <cell>10</cell>
            <cell>5</cell>
            <cell>2011-09-25</cell>
            <cell>Walt Dysney</cell>
            <cell>walt@dysney.com</cell>
            <cell>Dysney Inc</cell>
            <cell>$63,564.00</cell>
            <cell>In Progress</cell>
            <cell>2011-09-24</cell>
			<cell>Mike Rust</cell> 
        </row>
    </rows>