<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Account Detail</title>
</head>
Account Name: name_of_account <br/>
Account Executive: name_of_executive <br/>
Account Manager: name_of_manager <br/>
Country: country_name<br/>
Type of Account: type_of_account<br/>
<body>
</body>
</html>