<?xml version='1.0' encoding='iso-8859-1'?>
          <tree id="0"> 
              <item text="New" id="1" child="1" im0="new.gif" im1="new_dis.gif" im2="new_dis.gif" call="true" />
              <item text="Simple" id="2" child="1" im0="new.gif" im1="new_dis.gif" im2="new_dis.gif" call="true" />   
              <item text="List" id="3" child="0" im0="open.gif" im1="open_dis.gif" im2="open_dis.gif" call="true"/>
      </tree>