<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>New Invoice</title>
</head>
<body>
<form>
Project Number <input type="text" name="account_id" size="10" /> <br/>
Invoices will be created as part of a workflow item from project manage screen, this screen is for manual invoice creation per customer customozation
</form>
</body>
</html>