<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>New Quote</title>
</head>
<body>
<form>
Customer Name <input type="text" name="account_id" size="10" /> <br/>
Project Name <input type="text" name="account_id" size="10" /> <br/>
Project Start Date <input type="text" name="account_id" size="10" /> <br/>
Project End Date <input type="text" name="account_id" size="10" /> <br/>
Special Instructions <textarea></textarea>
<input type='reset' value='Reset' />
<input type='submit' value='Save' />

</form>
</body>
</html>