<?xml version="1.0" encoding="UTF-8"?>
<data>
        <item name="JC Penny" type="dir">
                <modifdate>2008-01-28 16-09-31</modifdate>
        </item>
        <item name="Reports" type="dir">
                <modifdate>2008-01-28 16-09-31</modifdate>
        </item>
        <item name="Test" type="dir">
                <modifdate>2008-01-28 16-09-31</modifdate>
        </item>
        <item name="Apple.jpg" type="file">
                <filesize>18637</filesize>
                <modifdate>2008-01-28 17-02-23</modifdate>
        </item>
</data>