<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>New Quote</title>
</head>
<body>
<form>
Account Name <input type="text" name="account_id" size="10" /> <br/>
Account Executive <input type="text" name="account_id" size="10" /> <br/>
Account Manager <input type="text" name="account_id" size="10" /> <br/>
Country <select name='country_id'>
			<option value=''>[Select]</option>
            <?php ?>
			</select> <br/>
Type of Account <select name='account_type_id'>
				<option value=''>[Select]</option>
                <option value=1>Lead</option>
                <option value=2>Prospect</option>
                <option value=3>Customer</option>
                <option value=4>Contractor</option>
				</select> <br/>
                
<input type='reset' value='Reset' />
<input type='submit' value='Save' />
</form>
</body>
</html>